### ISSUE TITLE
Is this a x-plat consumable solution?

### ISSUE THREAD

**Issue by cirvine-MSFT** [microsoft/CorrelationVector-Cpp#6]
My team needs a x-plat implementation of correlation vector in C or C++.
Squinting at the CMake files, it doesn't seem like this code is meant to be consumed out-of-the-box.
Is this something we would be inetersted in making consumable via source and/or vcpkg for x-plat consumers?
Is there any roadmap for this planned?

**Comment by mohit1234** [comment]
PR has been merged
